---
# LICENSE: Copyright (C) 2018 Abhishek Tamrakar
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
- name: create ansible directory structure
  file:
    path: "{{playbook_path}}/{{item}}"
    owner: "{{playbook_user}}"
    group: "{{playbook_group}}"
    mode: 0755
    state: directory
  with_items: "{{ansible_directories}}"
  tags: [create]

- name: create ansible role structure
  file:
    path: "{{playbook_path}}/roles/{{item[0]}}/{{item[1]}}"
    owner: "{{playbook_user}}"
    group: "{{playbook_group}}"
    mode: 0755
    state: directory
  with_nested:
    - "{{extras}}"
    - "{{ roles_directories }}"
  tags: [create]

- name: create default files.
  template:
    src: main.yml.j2
    dest: "{{playbook_path}}/roles/{{item[0]}}/{{item[1]}}/main.yml"
    owner: "{{playbook_user}}"
    group: "{{playbook_group}}"
    mode: 0644
  with_nested: 
    - "{{extras}}"
    - "{{ roles_directories }}"
  when: copy_default == 'yes'
  tags: [create]

- name: create default playbook.
  template:
    src: site.yml.j2
    dest: "{{playbook_path}}/site.yml"
    owner: "{{playbook_user}}"
    group: "{{playbook_group}}"
    mode: 0644
  when: copy_default == 'yes'
  tags: [create]
